"""Configuration loading for the JARVIS voice assistant.

The config file is generated by the Home Manager module (home/modules/jarvis.nix)
from Nix options, so everything here is declarative and rebuilt with the system.
Hand-editing ~/.config/jarvis/config.json works for experiments but is lost on the
next `home-manager` activation — change the Nix options instead.
"""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from pathlib import Path

DEFAULT_CONFIG_PATH = Path(
    os.environ.get("JARVIS_CONFIG", Path.home() / ".config/jarvis/config.json")
)


@dataclass
class WyomingEndpoint:
    host: str = "127.0.0.1"
    port: int = 10400

    @classmethod
    def parse(cls, raw: str) -> "WyomingEndpoint":
        """Accept "host:port" or a bare "tcp://host:port" URI."""
        raw = raw.removeprefix("tcp://")
        host, _, port = raw.rpartition(":")
        return cls(host=host or "127.0.0.1", port=int(port))


@dataclass
class BrainConfig:
    # "local"  — Ollama only, fully offline
    # "claude" — Anthropic API only
    # "hybrid" — local first, escalate to Claude for hard requests
    mode: str = "hybrid"

    ollama_host: str = "http://127.0.0.1:11434"
    local_model: str = "llama3.1:8b"

    claude_model: str = "claude-opus-5"
    # Voice replies are short by design, but the tool loop needs room to work.
    claude_max_tokens: int = 4096
    # "low" keeps latency conversational. Raise to "medium"/"high" if you want
    # the assistant to reason harder at the cost of a longer pause before it speaks.
    claude_effort: str = "low"
    # File containing ANTHROPIC_API_KEY=... or just the bare key. Kept out of the
    # Nix store — the HM module points this at a path you manage yourself.
    api_key_file: str | None = None

    # Escalate to Claude when the local model asks to, errors out, or when the
    # transcript matches one of these (case-insensitive substring) hints.
    escalate_hints: list[str] = field(default_factory=list)
    # Escalate anything longer than this many words — long requests are usually
    # the reasoning-heavy ones.
    escalate_word_count: int = 25


@dataclass
class ShellConfig:
    enabled: bool = True
    # Speak the command back and wait for a spoken "yes" before running it.
    # This is the guard against a misheard word becoming a real command.
    require_confirmation: bool = True
    # Regexes that are refused outright, confirmation or not.
    deny_patterns: list[str] = field(default_factory=list)
    timeout_seconds: int = 60


@dataclass
class Capabilities:
    conversation: bool = True
    desktop: bool = True
    system: bool = True
    nixos: bool = True
    shell: ShellConfig = field(default_factory=ShellConfig)


@dataclass
class Config:
    assistant_name: str = "JARVIS"
    user_name: str = "Sir"
    personality: str = ""

    wake_word: str = "hey_jarvis"
    wake_uri: str = "tcp://127.0.0.1:10400"
    asr_uri: str = "tcp://127.0.0.1:10300"
    tts_uri: str = "tcp://127.0.0.1:10200"
    tts_voice: str = "en_GB-alan-medium"

    # PortAudio device names; None means "system default".
    input_device: str | None = None
    output_device: str | None = None

    # How long a silence ends the user's turn, and how long we listen at most.
    silence_seconds: float = 1.2
    max_utterance_seconds: float = 20.0

    hud_enabled: bool = True
    hud_port: int = 8770

    brain: BrainConfig = field(default_factory=BrainConfig)
    capabilities: Capabilities = field(default_factory=Capabilities)

    @property
    def wake(self) -> WyomingEndpoint:
        return WyomingEndpoint.parse(self.wake_uri)

    @property
    def asr(self) -> WyomingEndpoint:
        return WyomingEndpoint.parse(self.asr_uri)

    @property
    def tts(self) -> WyomingEndpoint:
        return WyomingEndpoint.parse(self.tts_uri)

    def api_key(self) -> str | None:
        """Read the Anthropic key from disk, tolerating a KEY=value line."""
        if not self.brain.api_key_file:
            return os.environ.get("ANTHROPIC_API_KEY")
        path = Path(self.brain.api_key_file).expanduser()
        if not path.is_file():
            return os.environ.get("ANTHROPIC_API_KEY")
        text = path.read_text(encoding="utf-8").strip()
        if "=" in text.split("\n", 1)[0]:
            text = text.split("=", 1)[1].strip().strip("\"'")
        return text or None


def _build(cls, data: dict):
    """Instantiate a dataclass from a dict, ignoring unknown keys."""
    known = {f for f in cls.__dataclass_fields__}
    return cls(**{k: v for k, v in data.items() if k in known})


def load(path: Path | None = None) -> Config:
    path = path or DEFAULT_CONFIG_PATH
    if not path.is_file():
        return Config()

    raw = json.loads(path.read_text(encoding="utf-8"))

    brain = _build(BrainConfig, raw.pop("brain", {}))
    caps_raw = raw.pop("capabilities", {})
    shell = _build(ShellConfig, caps_raw.pop("shell", {}))
    caps = _build(Capabilities, caps_raw)
    caps.shell = shell

    cfg = _build(Config, raw)
    cfg.brain = brain
    cfg.capabilities = caps
    return cfg
